#!/usr/bin/env bash

display_usage() {
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if [ "$#" -lt 4 ]; then
	display_usage
	exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

if [ ! -f "$FILE_PATH" ]; then
	echo "Error: File '$FILE_PATH' not found."
	exit 1
fi

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~

if [ $? -eq 0 ]; then
	echo "$FILE_PATH transferred succesfully to $SERVER_IP"
else
	echo "Failed to transfer $FILE_PATH to $SERVER_IP"
fi
