#!/usr/bin/env bash
# This sript finds out what's keeping your ubuntu container's Nginx installation from listening to port 80

apt-get update -y
apt-get install -y nginx
sudo service nginx enable
sudo service nginx start
