#!/usr/bin/env bash
# This script dispalys a list of currently running processes
# Must show all processes, for all users, including those which might not have a TT
# Display in a user-oriented format
# Show process hierarchy
ps aux --forest
