#!/usr/bin/env bash
# script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009
pstree -p | grep --color=never bash
