#!/usr/bin/env bash
# This script installs the ufw firewall and set's up s few rules.

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable 
